// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditAdmin = `-- name: InsertAuditAdmin :one

INSERT INTO audit_admin (tenant_id, actor_id, action_type, target_type, target_id, change_summary)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, actor_id, action_type, target_type, target_id, change_summary, event_time, metadata
`

type InsertAuditAdminParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	ActorID       string      `json:"actor_id"`
	ActionType    string      `json:"action_type"`
	TargetType    pgtype.Text `json:"target_type"`
	TargetID      pgtype.Text `json:"target_id"`
	ChangeSummary pgtype.Text `json:"change_summary"`
}

// Audit admin events
// Source: db-schema.md §3.2
func (q *Queries) InsertAuditAdmin(ctx context.Context, arg InsertAuditAdminParams) (AuditAdmin, error) {
	row := q.db.QueryRow(ctx, insertAuditAdmin,
		arg.TenantID,
		arg.ActorID,
		arg.ActionType,
		arg.TargetType,
		arg.TargetID,
		arg.ChangeSummary,
	)
	var i AuditAdmin
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.ActionType,
		&i.TargetType,
		&i.TargetID,
		&i.ChangeSummary,
		&i.EventTime,
		&i.Metadata,
	)
	return i, err
}
