// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT (role_id, permission_id) DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (tenant_id, resource, action)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, resource, action) DO UPDATE SET resource = EXCLUDED.resource
RETURNING id, tenant_id, resource, action, created_at
`

type CreatePermissionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Resource string      `json:"resource"`
	Action   string      `json:"action"`
}

// Permissions and role_permissions queries
// Source: db-schema.md §§2.5, 2.6
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.TenantID, arg.Resource, arg.Action)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getPermissionByIDs = `-- name: GetPermissionByIDs :one
SELECT id, tenant_id, resource, action, created_at
FROM permissions
WHERE id = $1 AND tenant_id = $2
`

type GetPermissionByIDsParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPermissionByIDs(ctx context.Context, arg GetPermissionByIDsParams) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByIDs, arg.ID, arg.TenantID)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const getPermissionByTenantResourceAction = `-- name: GetPermissionByTenantResourceAction :one
SELECT id, tenant_id, resource, action, created_at
FROM permissions
WHERE tenant_id = $1 AND resource = $2 AND action = $3
`

type GetPermissionByTenantResourceActionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Resource string      `json:"resource"`
	Action   string      `json:"action"`
}

func (q *Queries) GetPermissionByTenantResourceAction(ctx context.Context, arg GetPermissionByTenantResourceActionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByTenantResourceAction, arg.TenantID, arg.Resource, arg.Action)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionsByRole = `-- name: ListPermissionsByRole :many
SELECT p.id, p.tenant_id, p.resource, p.action, p.created_at
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1 AND p.tenant_id = $2
`

type ListPermissionsByRoleParams struct {
	RoleID   pgtype.UUID `json:"role_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListPermissionsByRole(ctx context.Context, arg ListPermissionsByRoleParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRole, arg.RoleID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Resource,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRolePermission = `-- name: RemoveRolePermission :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RemoveRolePermissionParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error {
	_, err := q.db.Exec(ctx, removeRolePermission, arg.RoleID, arg.PermissionID)
	return err
}
