// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	// Permissions and role_permissions queries
	// Source: db-schema.md §§2.5, 2.6
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	// Roles CRUD queries
	// Source: db-schema.md §2.4
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteRolePermissions(ctx context.Context, roleID pgtype.UUID) error
	GetPermissionByIDs(ctx context.Context, arg GetPermissionByIDsParams) (Permission, error)
	GetPermissionByTenantResourceAction(ctx context.Context, arg GetPermissionByTenantResourceActionParams) (Permission, error)
	GetRole(ctx context.Context, arg GetRoleParams) (Role, error)
	GetRoleByNameAndTenant(ctx context.Context, arg GetRoleByNameAndTenantParams) (Role, error)
	// Tenants CRUD queries
	// Source: db-schema.md §2.1
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	// Audit admin events
	// Source: db-schema.md §3.2
	InsertAuditAdmin(ctx context.Context, arg InsertAuditAdminParams) (AuditAdmin, error)
	ListPermissionsByRole(ctx context.Context, arg ListPermissionsByRoleParams) ([]Permission, error)
	// Cursor: pass uuid.Nil or zero UUID for first page
	ListRolesByTenant(ctx context.Context, arg ListRolesByTenantParams) ([]Role, error)
	RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
