// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one

INSERT INTO roles (tenant_id, name, description, status, is_builtin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, description, status, is_builtin, created_at, updated_at
`

type CreateRoleParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	IsBuiltin   bool        `json:"is_builtin"`
}

// Roles CRUD queries
// Source: db-schema.md §2.4
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.IsBuiltin,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND tenant_id = $2
`

type DeleteRoleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.TenantID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, tenant_id, name, description, status, is_builtin, created_at, updated_at
FROM roles
WHERE id = $1 AND tenant_id = $2
`

type GetRoleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ID, arg.TenantID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByNameAndTenant = `-- name: GetRoleByNameAndTenant :one
SELECT id, tenant_id, name, description, status, is_builtin, created_at, updated_at
FROM roles
WHERE tenant_id = $1 AND name = $2
`

type GetRoleByNameAndTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
}

func (q *Queries) GetRoleByNameAndTenant(ctx context.Context, arg GetRoleByNameAndTenantParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByNameAndTenant, arg.TenantID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, tenant_id, name, description, status, is_builtin, created_at, updated_at
FROM roles
WHERE tenant_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListRolesByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Limit    int32       `json:"limit"`
}

// Cursor: pass uuid.Nil or zero UUID for first page
func (q *Queries) ListRolesByTenant(ctx context.Context, arg ListRolesByTenantParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByTenant, arg.TenantID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.IsBuiltin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3, status = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $5
RETURNING id, tenant_id, name, description, status, is_builtin, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.TenantID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.IsBuiltin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
