// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTenant = `-- name: GetTenant :one

SELECT id, name, created_at
FROM tenants
WHERE id = $1
`

// Tenants CRUD queries
// Source: db-schema.md §2.1
func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
